// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: launcher_trace_file.proto

package com.android.launcher3.tracing;

/**
 * <pre>
 * one launcher trace entry. 
 * </pre>
 *
 * Protobuf type {@code com.android.launcher3.tracing.LauncherTraceEntryProto}
 */
public final class LauncherTraceEntryProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.android.launcher3.tracing.LauncherTraceEntryProto)
    LauncherTraceEntryProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LauncherTraceEntryProto.newBuilder() to construct.
  private LauncherTraceEntryProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LauncherTraceEntryProto() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new LauncherTraceEntryProto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private LauncherTraceEntryProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 9: {
            bitField0_ |= 0x00000001;
            elapsedRealtimeNanos_ = input.readFixed64();
            break;
          }
          case 26: {
            com.android.launcher3.tracing.LauncherTraceProto.Builder subBuilder = null;
            if (((bitField0_ & 0x00000002) != 0)) {
              subBuilder = launcher_.toBuilder();
            }
            launcher_ = input.readMessage(com.android.launcher3.tracing.LauncherTraceProto.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(launcher_);
              launcher_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000002;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.android.launcher3.tracing.LauncherTraceFile.internal_static_com_android_launcher3_tracing_LauncherTraceEntryProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.android.launcher3.tracing.LauncherTraceFile.internal_static_com_android_launcher3_tracing_LauncherTraceEntryProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.android.launcher3.tracing.LauncherTraceEntryProto.class, com.android.launcher3.tracing.LauncherTraceEntryProto.Builder.class);
  }

  private int bitField0_;
  public static final int ELAPSED_REALTIME_NANOS_FIELD_NUMBER = 1;
  private long elapsedRealtimeNanos_;
  /**
   * <pre>
   * required: elapsed realtime in nanos since boot of when this entry was logged 
   * </pre>
   *
   * <code>optional fixed64 elapsed_realtime_nanos = 1;</code>
   * @return Whether the elapsedRealtimeNanos field is set.
   */
  @java.lang.Override
  public boolean hasElapsedRealtimeNanos() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * required: elapsed realtime in nanos since boot of when this entry was logged 
   * </pre>
   *
   * <code>optional fixed64 elapsed_realtime_nanos = 1;</code>
   * @return The elapsedRealtimeNanos.
   */
  @java.lang.Override
  public long getElapsedRealtimeNanos() {
    return elapsedRealtimeNanos_;
  }

  public static final int LAUNCHER_FIELD_NUMBER = 3;
  private com.android.launcher3.tracing.LauncherTraceProto launcher_;
  /**
   * <code>optional .com.android.launcher3.tracing.LauncherTraceProto launcher = 3;</code>
   * @return Whether the launcher field is set.
   */
  @java.lang.Override
  public boolean hasLauncher() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional .com.android.launcher3.tracing.LauncherTraceProto launcher = 3;</code>
   * @return The launcher.
   */
  @java.lang.Override
  public com.android.launcher3.tracing.LauncherTraceProto getLauncher() {
    return launcher_ == null ? com.android.launcher3.tracing.LauncherTraceProto.getDefaultInstance() : launcher_;
  }
  /**
   * <code>optional .com.android.launcher3.tracing.LauncherTraceProto launcher = 3;</code>
   */
  @java.lang.Override
  public com.android.launcher3.tracing.LauncherTraceProtoOrBuilder getLauncherOrBuilder() {
    return launcher_ == null ? com.android.launcher3.tracing.LauncherTraceProto.getDefaultInstance() : launcher_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeFixed64(1, elapsedRealtimeNanos_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(3, getLauncher());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeFixed64Size(1, elapsedRealtimeNanos_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getLauncher());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.android.launcher3.tracing.LauncherTraceEntryProto)) {
      return super.equals(obj);
    }
    com.android.launcher3.tracing.LauncherTraceEntryProto other = (com.android.launcher3.tracing.LauncherTraceEntryProto) obj;

    if (hasElapsedRealtimeNanos() != other.hasElapsedRealtimeNanos()) return false;
    if (hasElapsedRealtimeNanos()) {
      if (getElapsedRealtimeNanos()
          != other.getElapsedRealtimeNanos()) return false;
    }
    if (hasLauncher() != other.hasLauncher()) return false;
    if (hasLauncher()) {
      if (!getLauncher()
          .equals(other.getLauncher())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasElapsedRealtimeNanos()) {
      hash = (37 * hash) + ELAPSED_REALTIME_NANOS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getElapsedRealtimeNanos());
    }
    if (hasLauncher()) {
      hash = (37 * hash) + LAUNCHER_FIELD_NUMBER;
      hash = (53 * hash) + getLauncher().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.android.launcher3.tracing.LauncherTraceEntryProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.android.launcher3.tracing.LauncherTraceEntryProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.android.launcher3.tracing.LauncherTraceEntryProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.android.launcher3.tracing.LauncherTraceEntryProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.android.launcher3.tracing.LauncherTraceEntryProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.android.launcher3.tracing.LauncherTraceEntryProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.android.launcher3.tracing.LauncherTraceEntryProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.android.launcher3.tracing.LauncherTraceEntryProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.android.launcher3.tracing.LauncherTraceEntryProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.android.launcher3.tracing.LauncherTraceEntryProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.android.launcher3.tracing.LauncherTraceEntryProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.android.launcher3.tracing.LauncherTraceEntryProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.android.launcher3.tracing.LauncherTraceEntryProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * one launcher trace entry. 
   * </pre>
   *
   * Protobuf type {@code com.android.launcher3.tracing.LauncherTraceEntryProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.android.launcher3.tracing.LauncherTraceEntryProto)
      com.android.launcher3.tracing.LauncherTraceEntryProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.android.launcher3.tracing.LauncherTraceFile.internal_static_com_android_launcher3_tracing_LauncherTraceEntryProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.android.launcher3.tracing.LauncherTraceFile.internal_static_com_android_launcher3_tracing_LauncherTraceEntryProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.android.launcher3.tracing.LauncherTraceEntryProto.class, com.android.launcher3.tracing.LauncherTraceEntryProto.Builder.class);
    }

    // Construct using com.android.launcher3.tracing.LauncherTraceEntryProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getLauncherFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      elapsedRealtimeNanos_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000001);
      if (launcherBuilder_ == null) {
        launcher_ = null;
      } else {
        launcherBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.android.launcher3.tracing.LauncherTraceFile.internal_static_com_android_launcher3_tracing_LauncherTraceEntryProto_descriptor;
    }

    @java.lang.Override
    public com.android.launcher3.tracing.LauncherTraceEntryProto getDefaultInstanceForType() {
      return com.android.launcher3.tracing.LauncherTraceEntryProto.getDefaultInstance();
    }

    @java.lang.Override
    public com.android.launcher3.tracing.LauncherTraceEntryProto build() {
      com.android.launcher3.tracing.LauncherTraceEntryProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.android.launcher3.tracing.LauncherTraceEntryProto buildPartial() {
      com.android.launcher3.tracing.LauncherTraceEntryProto result = new com.android.launcher3.tracing.LauncherTraceEntryProto(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.elapsedRealtimeNanos_ = elapsedRealtimeNanos_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        if (launcherBuilder_ == null) {
          result.launcher_ = launcher_;
        } else {
          result.launcher_ = launcherBuilder_.build();
        }
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.android.launcher3.tracing.LauncherTraceEntryProto) {
        return mergeFrom((com.android.launcher3.tracing.LauncherTraceEntryProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.android.launcher3.tracing.LauncherTraceEntryProto other) {
      if (other == com.android.launcher3.tracing.LauncherTraceEntryProto.getDefaultInstance()) return this;
      if (other.hasElapsedRealtimeNanos()) {
        setElapsedRealtimeNanos(other.getElapsedRealtimeNanos());
      }
      if (other.hasLauncher()) {
        mergeLauncher(other.getLauncher());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.android.launcher3.tracing.LauncherTraceEntryProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.android.launcher3.tracing.LauncherTraceEntryProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long elapsedRealtimeNanos_ ;
    /**
     * <pre>
     * required: elapsed realtime in nanos since boot of when this entry was logged 
     * </pre>
     *
     * <code>optional fixed64 elapsed_realtime_nanos = 1;</code>
     * @return Whether the elapsedRealtimeNanos field is set.
     */
    @java.lang.Override
    public boolean hasElapsedRealtimeNanos() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * required: elapsed realtime in nanos since boot of when this entry was logged 
     * </pre>
     *
     * <code>optional fixed64 elapsed_realtime_nanos = 1;</code>
     * @return The elapsedRealtimeNanos.
     */
    @java.lang.Override
    public long getElapsedRealtimeNanos() {
      return elapsedRealtimeNanos_;
    }
    /**
     * <pre>
     * required: elapsed realtime in nanos since boot of when this entry was logged 
     * </pre>
     *
     * <code>optional fixed64 elapsed_realtime_nanos = 1;</code>
     * @param value The elapsedRealtimeNanos to set.
     * @return This builder for chaining.
     */
    public Builder setElapsedRealtimeNanos(long value) {
      bitField0_ |= 0x00000001;
      elapsedRealtimeNanos_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * required: elapsed realtime in nanos since boot of when this entry was logged 
     * </pre>
     *
     * <code>optional fixed64 elapsed_realtime_nanos = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearElapsedRealtimeNanos() {
      bitField0_ = (bitField0_ & ~0x00000001);
      elapsedRealtimeNanos_ = 0L;
      onChanged();
      return this;
    }

    private com.android.launcher3.tracing.LauncherTraceProto launcher_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.android.launcher3.tracing.LauncherTraceProto, com.android.launcher3.tracing.LauncherTraceProto.Builder, com.android.launcher3.tracing.LauncherTraceProtoOrBuilder> launcherBuilder_;
    /**
     * <code>optional .com.android.launcher3.tracing.LauncherTraceProto launcher = 3;</code>
     * @return Whether the launcher field is set.
     */
    public boolean hasLauncher() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .com.android.launcher3.tracing.LauncherTraceProto launcher = 3;</code>
     * @return The launcher.
     */
    public com.android.launcher3.tracing.LauncherTraceProto getLauncher() {
      if (launcherBuilder_ == null) {
        return launcher_ == null ? com.android.launcher3.tracing.LauncherTraceProto.getDefaultInstance() : launcher_;
      } else {
        return launcherBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .com.android.launcher3.tracing.LauncherTraceProto launcher = 3;</code>
     */
    public Builder setLauncher(com.android.launcher3.tracing.LauncherTraceProto value) {
      if (launcherBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        launcher_ = value;
        onChanged();
      } else {
        launcherBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>optional .com.android.launcher3.tracing.LauncherTraceProto launcher = 3;</code>
     */
    public Builder setLauncher(
        com.android.launcher3.tracing.LauncherTraceProto.Builder builderForValue) {
      if (launcherBuilder_ == null) {
        launcher_ = builderForValue.build();
        onChanged();
      } else {
        launcherBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>optional .com.android.launcher3.tracing.LauncherTraceProto launcher = 3;</code>
     */
    public Builder mergeLauncher(com.android.launcher3.tracing.LauncherTraceProto value) {
      if (launcherBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
            launcher_ != null &&
            launcher_ != com.android.launcher3.tracing.LauncherTraceProto.getDefaultInstance()) {
          launcher_ =
            com.android.launcher3.tracing.LauncherTraceProto.newBuilder(launcher_).mergeFrom(value).buildPartial();
        } else {
          launcher_ = value;
        }
        onChanged();
      } else {
        launcherBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>optional .com.android.launcher3.tracing.LauncherTraceProto launcher = 3;</code>
     */
    public Builder clearLauncher() {
      if (launcherBuilder_ == null) {
        launcher_ = null;
        onChanged();
      } else {
        launcherBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }
    /**
     * <code>optional .com.android.launcher3.tracing.LauncherTraceProto launcher = 3;</code>
     */
    public com.android.launcher3.tracing.LauncherTraceProto.Builder getLauncherBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getLauncherFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .com.android.launcher3.tracing.LauncherTraceProto launcher = 3;</code>
     */
    public com.android.launcher3.tracing.LauncherTraceProtoOrBuilder getLauncherOrBuilder() {
      if (launcherBuilder_ != null) {
        return launcherBuilder_.getMessageOrBuilder();
      } else {
        return launcher_ == null ?
            com.android.launcher3.tracing.LauncherTraceProto.getDefaultInstance() : launcher_;
      }
    }
    /**
     * <code>optional .com.android.launcher3.tracing.LauncherTraceProto launcher = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.android.launcher3.tracing.LauncherTraceProto, com.android.launcher3.tracing.LauncherTraceProto.Builder, com.android.launcher3.tracing.LauncherTraceProtoOrBuilder> 
        getLauncherFieldBuilder() {
      if (launcherBuilder_ == null) {
        launcherBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.android.launcher3.tracing.LauncherTraceProto, com.android.launcher3.tracing.LauncherTraceProto.Builder, com.android.launcher3.tracing.LauncherTraceProtoOrBuilder>(
                getLauncher(),
                getParentForChildren(),
                isClean());
        launcher_ = null;
      }
      return launcherBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.android.launcher3.tracing.LauncherTraceEntryProto)
  }

  // @@protoc_insertion_point(class_scope:com.android.launcher3.tracing.LauncherTraceEntryProto)
  private static final com.android.launcher3.tracing.LauncherTraceEntryProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.android.launcher3.tracing.LauncherTraceEntryProto();
  }

  public static com.android.launcher3.tracing.LauncherTraceEntryProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<LauncherTraceEntryProto>
      PARSER = new com.google.protobuf.AbstractParser<LauncherTraceEntryProto>() {
    @java.lang.Override
    public LauncherTraceEntryProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new LauncherTraceEntryProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LauncherTraceEntryProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LauncherTraceEntryProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.android.launcher3.tracing.LauncherTraceEntryProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

