// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: launcher_trace.proto

package com.android.launcher3.tracing;

/**
 * Protobuf type {@code com.android.launcher3.tracing.LauncherTraceProto}
 */
public final class LauncherTraceProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.android.launcher3.tracing.LauncherTraceProto)
    LauncherTraceProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LauncherTraceProto.newBuilder() to construct.
  private LauncherTraceProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LauncherTraceProto() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new LauncherTraceProto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private LauncherTraceProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.android.launcher3.tracing.TouchInteractionServiceProto.Builder subBuilder = null;
            if (((bitField0_ & 0x00000001) != 0)) {
              subBuilder = touchInteractionService_.toBuilder();
            }
            touchInteractionService_ = input.readMessage(com.android.launcher3.tracing.TouchInteractionServiceProto.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(touchInteractionService_);
              touchInteractionService_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000001;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.android.launcher3.tracing.LauncherTrace.internal_static_com_android_launcher3_tracing_LauncherTraceProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.android.launcher3.tracing.LauncherTrace.internal_static_com_android_launcher3_tracing_LauncherTraceProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.android.launcher3.tracing.LauncherTraceProto.class, com.android.launcher3.tracing.LauncherTraceProto.Builder.class);
  }

  private int bitField0_;
  public static final int TOUCH_INTERACTION_SERVICE_FIELD_NUMBER = 1;
  private com.android.launcher3.tracing.TouchInteractionServiceProto touchInteractionService_;
  /**
   * <code>optional .com.android.launcher3.tracing.TouchInteractionServiceProto touch_interaction_service = 1;</code>
   * @return Whether the touchInteractionService field is set.
   */
  @java.lang.Override
  public boolean hasTouchInteractionService() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional .com.android.launcher3.tracing.TouchInteractionServiceProto touch_interaction_service = 1;</code>
   * @return The touchInteractionService.
   */
  @java.lang.Override
  public com.android.launcher3.tracing.TouchInteractionServiceProto getTouchInteractionService() {
    return touchInteractionService_ == null ? com.android.launcher3.tracing.TouchInteractionServiceProto.getDefaultInstance() : touchInteractionService_;
  }
  /**
   * <code>optional .com.android.launcher3.tracing.TouchInteractionServiceProto touch_interaction_service = 1;</code>
   */
  @java.lang.Override
  public com.android.launcher3.tracing.TouchInteractionServiceProtoOrBuilder getTouchInteractionServiceOrBuilder() {
    return touchInteractionService_ == null ? com.android.launcher3.tracing.TouchInteractionServiceProto.getDefaultInstance() : touchInteractionService_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getTouchInteractionService());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getTouchInteractionService());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.android.launcher3.tracing.LauncherTraceProto)) {
      return super.equals(obj);
    }
    com.android.launcher3.tracing.LauncherTraceProto other = (com.android.launcher3.tracing.LauncherTraceProto) obj;

    if (hasTouchInteractionService() != other.hasTouchInteractionService()) return false;
    if (hasTouchInteractionService()) {
      if (!getTouchInteractionService()
          .equals(other.getTouchInteractionService())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasTouchInteractionService()) {
      hash = (37 * hash) + TOUCH_INTERACTION_SERVICE_FIELD_NUMBER;
      hash = (53 * hash) + getTouchInteractionService().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.android.launcher3.tracing.LauncherTraceProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.android.launcher3.tracing.LauncherTraceProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.android.launcher3.tracing.LauncherTraceProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.android.launcher3.tracing.LauncherTraceProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.android.launcher3.tracing.LauncherTraceProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.android.launcher3.tracing.LauncherTraceProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.android.launcher3.tracing.LauncherTraceProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.android.launcher3.tracing.LauncherTraceProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.android.launcher3.tracing.LauncherTraceProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.android.launcher3.tracing.LauncherTraceProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.android.launcher3.tracing.LauncherTraceProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.android.launcher3.tracing.LauncherTraceProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.android.launcher3.tracing.LauncherTraceProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.android.launcher3.tracing.LauncherTraceProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.android.launcher3.tracing.LauncherTraceProto)
      com.android.launcher3.tracing.LauncherTraceProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.android.launcher3.tracing.LauncherTrace.internal_static_com_android_launcher3_tracing_LauncherTraceProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.android.launcher3.tracing.LauncherTrace.internal_static_com_android_launcher3_tracing_LauncherTraceProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.android.launcher3.tracing.LauncherTraceProto.class, com.android.launcher3.tracing.LauncherTraceProto.Builder.class);
    }

    // Construct using com.android.launcher3.tracing.LauncherTraceProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getTouchInteractionServiceFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (touchInteractionServiceBuilder_ == null) {
        touchInteractionService_ = null;
      } else {
        touchInteractionServiceBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.android.launcher3.tracing.LauncherTrace.internal_static_com_android_launcher3_tracing_LauncherTraceProto_descriptor;
    }

    @java.lang.Override
    public com.android.launcher3.tracing.LauncherTraceProto getDefaultInstanceForType() {
      return com.android.launcher3.tracing.LauncherTraceProto.getDefaultInstance();
    }

    @java.lang.Override
    public com.android.launcher3.tracing.LauncherTraceProto build() {
      com.android.launcher3.tracing.LauncherTraceProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.android.launcher3.tracing.LauncherTraceProto buildPartial() {
      com.android.launcher3.tracing.LauncherTraceProto result = new com.android.launcher3.tracing.LauncherTraceProto(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        if (touchInteractionServiceBuilder_ == null) {
          result.touchInteractionService_ = touchInteractionService_;
        } else {
          result.touchInteractionService_ = touchInteractionServiceBuilder_.build();
        }
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.android.launcher3.tracing.LauncherTraceProto) {
        return mergeFrom((com.android.launcher3.tracing.LauncherTraceProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.android.launcher3.tracing.LauncherTraceProto other) {
      if (other == com.android.launcher3.tracing.LauncherTraceProto.getDefaultInstance()) return this;
      if (other.hasTouchInteractionService()) {
        mergeTouchInteractionService(other.getTouchInteractionService());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.android.launcher3.tracing.LauncherTraceProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.android.launcher3.tracing.LauncherTraceProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.android.launcher3.tracing.TouchInteractionServiceProto touchInteractionService_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.android.launcher3.tracing.TouchInteractionServiceProto, com.android.launcher3.tracing.TouchInteractionServiceProto.Builder, com.android.launcher3.tracing.TouchInteractionServiceProtoOrBuilder> touchInteractionServiceBuilder_;
    /**
     * <code>optional .com.android.launcher3.tracing.TouchInteractionServiceProto touch_interaction_service = 1;</code>
     * @return Whether the touchInteractionService field is set.
     */
    public boolean hasTouchInteractionService() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .com.android.launcher3.tracing.TouchInteractionServiceProto touch_interaction_service = 1;</code>
     * @return The touchInteractionService.
     */
    public com.android.launcher3.tracing.TouchInteractionServiceProto getTouchInteractionService() {
      if (touchInteractionServiceBuilder_ == null) {
        return touchInteractionService_ == null ? com.android.launcher3.tracing.TouchInteractionServiceProto.getDefaultInstance() : touchInteractionService_;
      } else {
        return touchInteractionServiceBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .com.android.launcher3.tracing.TouchInteractionServiceProto touch_interaction_service = 1;</code>
     */
    public Builder setTouchInteractionService(com.android.launcher3.tracing.TouchInteractionServiceProto value) {
      if (touchInteractionServiceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        touchInteractionService_ = value;
        onChanged();
      } else {
        touchInteractionServiceBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>optional .com.android.launcher3.tracing.TouchInteractionServiceProto touch_interaction_service = 1;</code>
     */
    public Builder setTouchInteractionService(
        com.android.launcher3.tracing.TouchInteractionServiceProto.Builder builderForValue) {
      if (touchInteractionServiceBuilder_ == null) {
        touchInteractionService_ = builderForValue.build();
        onChanged();
      } else {
        touchInteractionServiceBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>optional .com.android.launcher3.tracing.TouchInteractionServiceProto touch_interaction_service = 1;</code>
     */
    public Builder mergeTouchInteractionService(com.android.launcher3.tracing.TouchInteractionServiceProto value) {
      if (touchInteractionServiceBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
            touchInteractionService_ != null &&
            touchInteractionService_ != com.android.launcher3.tracing.TouchInteractionServiceProto.getDefaultInstance()) {
          touchInteractionService_ =
            com.android.launcher3.tracing.TouchInteractionServiceProto.newBuilder(touchInteractionService_).mergeFrom(value).buildPartial();
        } else {
          touchInteractionService_ = value;
        }
        onChanged();
      } else {
        touchInteractionServiceBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>optional .com.android.launcher3.tracing.TouchInteractionServiceProto touch_interaction_service = 1;</code>
     */
    public Builder clearTouchInteractionService() {
      if (touchInteractionServiceBuilder_ == null) {
        touchInteractionService_ = null;
        onChanged();
      } else {
        touchInteractionServiceBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }
    /**
     * <code>optional .com.android.launcher3.tracing.TouchInteractionServiceProto touch_interaction_service = 1;</code>
     */
    public com.android.launcher3.tracing.TouchInteractionServiceProto.Builder getTouchInteractionServiceBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getTouchInteractionServiceFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .com.android.launcher3.tracing.TouchInteractionServiceProto touch_interaction_service = 1;</code>
     */
    public com.android.launcher3.tracing.TouchInteractionServiceProtoOrBuilder getTouchInteractionServiceOrBuilder() {
      if (touchInteractionServiceBuilder_ != null) {
        return touchInteractionServiceBuilder_.getMessageOrBuilder();
      } else {
        return touchInteractionService_ == null ?
            com.android.launcher3.tracing.TouchInteractionServiceProto.getDefaultInstance() : touchInteractionService_;
      }
    }
    /**
     * <code>optional .com.android.launcher3.tracing.TouchInteractionServiceProto touch_interaction_service = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.android.launcher3.tracing.TouchInteractionServiceProto, com.android.launcher3.tracing.TouchInteractionServiceProto.Builder, com.android.launcher3.tracing.TouchInteractionServiceProtoOrBuilder> 
        getTouchInteractionServiceFieldBuilder() {
      if (touchInteractionServiceBuilder_ == null) {
        touchInteractionServiceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.android.launcher3.tracing.TouchInteractionServiceProto, com.android.launcher3.tracing.TouchInteractionServiceProto.Builder, com.android.launcher3.tracing.TouchInteractionServiceProtoOrBuilder>(
                getTouchInteractionService(),
                getParentForChildren(),
                isClean());
        touchInteractionService_ = null;
      }
      return touchInteractionServiceBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.android.launcher3.tracing.LauncherTraceProto)
  }

  // @@protoc_insertion_point(class_scope:com.android.launcher3.tracing.LauncherTraceProto)
  private static final com.android.launcher3.tracing.LauncherTraceProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.android.launcher3.tracing.LauncherTraceProto();
  }

  public static com.android.launcher3.tracing.LauncherTraceProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<LauncherTraceProto>
      PARSER = new com.google.protobuf.AbstractParser<LauncherTraceProto>() {
    @java.lang.Override
    public LauncherTraceProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new LauncherTraceProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LauncherTraceProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LauncherTraceProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.android.launcher3.tracing.LauncherTraceProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

