// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: launcher_trace_file.proto

package com.android.launcher3.tracing;

public final class LauncherTraceFile {
  private LauncherTraceFile() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_android_launcher3_tracing_LauncherTraceFileProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_android_launcher3_tracing_LauncherTraceFileProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_android_launcher3_tracing_LauncherTraceEntryProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_android_launcher3_tracing_LauncherTraceEntryProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031launcher_trace_file.proto\022\035com.android" +
      ".launcher3.tracing\032\024launcher_trace.proto" +
      "\"\301\001\n\026LauncherTraceFileProto\022\024\n\014magic_num" +
      "ber\030\001 \001(\006\022E\n\005entry\030\002 \003(\01326.com.android.l" +
      "auncher3.tracing.LauncherTraceEntryProto" +
      "\"J\n\013MagicNumber\022\013\n\007INVALID\020\000\022\026\n\016MAGIC_NU" +
      "MBER_L\020\314\234\215\302\004\022\026\n\016MAGIC_NUMBER_H\020\322\250\311\232\004\"~\n\027" +
      "LauncherTraceEntryProto\022\036\n\026elapsed_realt" +
      "ime_nanos\030\001 \001(\006\022C\n\010launcher\030\003 \001(\01321.com." +
      "android.launcher3.tracing.LauncherTraceP" +
      "rotoB\002P\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.android.launcher3.tracing.LauncherTrace.getDescriptor(),
        });
    internal_static_com_android_launcher3_tracing_LauncherTraceFileProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_android_launcher3_tracing_LauncherTraceFileProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_android_launcher3_tracing_LauncherTraceFileProto_descriptor,
        new java.lang.String[] { "MagicNumber", "Entry", });
    internal_static_com_android_launcher3_tracing_LauncherTraceEntryProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_android_launcher3_tracing_LauncherTraceEntryProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_android_launcher3_tracing_LauncherTraceEntryProto_descriptor,
        new java.lang.String[] { "ElapsedRealtimeNanos", "Launcher", });
    com.android.launcher3.tracing.LauncherTrace.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
