// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: launcher_trace.proto

package com.android.launcher3.tracing;

public final class LauncherTrace {
  private LauncherTrace() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_android_launcher3_tracing_LauncherTraceProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_android_launcher3_tracing_LauncherTraceProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_android_launcher3_tracing_TouchInteractionServiceProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_android_launcher3_tracing_TouchInteractionServiceProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024launcher_trace.proto\022\035com.android.laun" +
      "cher3.tracing\"t\n\022LauncherTraceProto\022^\n\031t" +
      "ouch_interaction_service\030\001 \001(\0132;.com.and" +
      "roid.launcher3.tracing.TouchInteractionS" +
      "erviceProto\"9\n\034TouchInteractionServicePr" +
      "oto\022\031\n\021service_connected\030\001 \001(\010B\002P\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_android_launcher3_tracing_LauncherTraceProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_android_launcher3_tracing_LauncherTraceProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_android_launcher3_tracing_LauncherTraceProto_descriptor,
        new java.lang.String[] { "TouchInteractionService", });
    internal_static_com_android_launcher3_tracing_TouchInteractionServiceProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_android_launcher3_tracing_TouchInteractionServiceProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_android_launcher3_tracing_TouchInteractionServiceProto_descriptor,
        new java.lang.String[] { "ServiceConnected", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
