// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: launcher_trace_file.proto

package com.android.launcher3.tracing;

public interface LauncherTraceFileProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.android.launcher3.tracing.LauncherTraceFileProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Must be the first field, set to value in MagicNumber 
   * </pre>
   *
   * <code>optional fixed64 magic_number = 1;</code>
   * @return Whether the magicNumber field is set.
   */
  boolean hasMagicNumber();
  /**
   * <pre>
   * Must be the first field, set to value in MagicNumber 
   * </pre>
   *
   * <code>optional fixed64 magic_number = 1;</code>
   * @return The magicNumber.
   */
  long getMagicNumber();

  /**
   * <code>repeated .com.android.launcher3.tracing.LauncherTraceEntryProto entry = 2;</code>
   */
  java.util.List<com.android.launcher3.tracing.LauncherTraceEntryProto> 
      getEntryList();
  /**
   * <code>repeated .com.android.launcher3.tracing.LauncherTraceEntryProto entry = 2;</code>
   */
  com.android.launcher3.tracing.LauncherTraceEntryProto getEntry(int index);
  /**
   * <code>repeated .com.android.launcher3.tracing.LauncherTraceEntryProto entry = 2;</code>
   */
  int getEntryCount();
  /**
   * <code>repeated .com.android.launcher3.tracing.LauncherTraceEntryProto entry = 2;</code>
   */
  java.util.List<? extends com.android.launcher3.tracing.LauncherTraceEntryProtoOrBuilder> 
      getEntryOrBuilderList();
  /**
   * <code>repeated .com.android.launcher3.tracing.LauncherTraceEntryProto entry = 2;</code>
   */
  com.android.launcher3.tracing.LauncherTraceEntryProtoOrBuilder getEntryOrBuilder(
      int index);
}
