// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: launcher_trace.proto

package com.android.launcher3.tracing;

public interface LauncherTraceProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.android.launcher3.tracing.LauncherTraceProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .com.android.launcher3.tracing.TouchInteractionServiceProto touch_interaction_service = 1;</code>
   * @return Whether the touchInteractionService field is set.
   */
  boolean hasTouchInteractionService();
  /**
   * <code>optional .com.android.launcher3.tracing.TouchInteractionServiceProto touch_interaction_service = 1;</code>
   * @return The touchInteractionService.
   */
  com.android.launcher3.tracing.TouchInteractionServiceProto getTouchInteractionService();
  /**
   * <code>optional .com.android.launcher3.tracing.TouchInteractionServiceProto touch_interaction_service = 1;</code>
   */
  com.android.launcher3.tracing.TouchInteractionServiceProtoOrBuilder getTouchInteractionServiceOrBuilder();
}
