// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: launcher_trace_file.proto

package com.android.launcher3.tracing;

public interface LauncherTraceEntryProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.android.launcher3.tracing.LauncherTraceEntryProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * required: elapsed realtime in nanos since boot of when this entry was logged 
   * </pre>
   *
   * <code>optional fixed64 elapsed_realtime_nanos = 1;</code>
   * @return Whether the elapsedRealtimeNanos field is set.
   */
  boolean hasElapsedRealtimeNanos();
  /**
   * <pre>
   * required: elapsed realtime in nanos since boot of when this entry was logged 
   * </pre>
   *
   * <code>optional fixed64 elapsed_realtime_nanos = 1;</code>
   * @return The elapsedRealtimeNanos.
   */
  long getElapsedRealtimeNanos();

  /**
   * <code>optional .com.android.launcher3.tracing.LauncherTraceProto launcher = 3;</code>
   * @return Whether the launcher field is set.
   */
  boolean hasLauncher();
  /**
   * <code>optional .com.android.launcher3.tracing.LauncherTraceProto launcher = 3;</code>
   * @return The launcher.
   */
  com.android.launcher3.tracing.LauncherTraceProto getLauncher();
  /**
   * <code>optional .com.android.launcher3.tracing.LauncherTraceProto launcher = 3;</code>
   */
  com.android.launcher3.tracing.LauncherTraceProtoOrBuilder getLauncherOrBuilder();
}
