// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: launcher_trace.proto

package com.android.launcher3.tracing;

public interface TouchInteractionServiceProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.android.launcher3.tracing.TouchInteractionServiceProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bool service_connected = 1;</code>
   * @return Whether the serviceConnected field is set.
   */
  boolean hasServiceConnected();
  /**
   * <code>optional bool service_connected = 1;</code>
   * @return The serviceConnected.
   */
  boolean getServiceConnected();
}
