// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: launcher_trace.proto

package com.android.launcher3.tracing;

/**
 * Protobuf type {@code com.android.launcher3.tracing.TouchInteractionServiceProto}
 */
public final class TouchInteractionServiceProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.android.launcher3.tracing.TouchInteractionServiceProto)
    TouchInteractionServiceProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TouchInteractionServiceProto.newBuilder() to construct.
  private TouchInteractionServiceProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TouchInteractionServiceProto() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TouchInteractionServiceProto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TouchInteractionServiceProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            bitField0_ |= 0x00000001;
            serviceConnected_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.android.launcher3.tracing.LauncherTrace.internal_static_com_android_launcher3_tracing_TouchInteractionServiceProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.android.launcher3.tracing.LauncherTrace.internal_static_com_android_launcher3_tracing_TouchInteractionServiceProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.android.launcher3.tracing.TouchInteractionServiceProto.class, com.android.launcher3.tracing.TouchInteractionServiceProto.Builder.class);
  }

  private int bitField0_;
  public static final int SERVICE_CONNECTED_FIELD_NUMBER = 1;
  private boolean serviceConnected_;
  /**
   * <code>optional bool service_connected = 1;</code>
   * @return Whether the serviceConnected field is set.
   */
  @java.lang.Override
  public boolean hasServiceConnected() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional bool service_connected = 1;</code>
   * @return The serviceConnected.
   */
  @java.lang.Override
  public boolean getServiceConnected() {
    return serviceConnected_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeBool(1, serviceConnected_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, serviceConnected_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.android.launcher3.tracing.TouchInteractionServiceProto)) {
      return super.equals(obj);
    }
    com.android.launcher3.tracing.TouchInteractionServiceProto other = (com.android.launcher3.tracing.TouchInteractionServiceProto) obj;

    if (hasServiceConnected() != other.hasServiceConnected()) return false;
    if (hasServiceConnected()) {
      if (getServiceConnected()
          != other.getServiceConnected()) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasServiceConnected()) {
      hash = (37 * hash) + SERVICE_CONNECTED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getServiceConnected());
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.android.launcher3.tracing.TouchInteractionServiceProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.android.launcher3.tracing.TouchInteractionServiceProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.android.launcher3.tracing.TouchInteractionServiceProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.android.launcher3.tracing.TouchInteractionServiceProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.android.launcher3.tracing.TouchInteractionServiceProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.android.launcher3.tracing.TouchInteractionServiceProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.android.launcher3.tracing.TouchInteractionServiceProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.android.launcher3.tracing.TouchInteractionServiceProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.android.launcher3.tracing.TouchInteractionServiceProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.android.launcher3.tracing.TouchInteractionServiceProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.android.launcher3.tracing.TouchInteractionServiceProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.android.launcher3.tracing.TouchInteractionServiceProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.android.launcher3.tracing.TouchInteractionServiceProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.android.launcher3.tracing.TouchInteractionServiceProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.android.launcher3.tracing.TouchInteractionServiceProto)
      com.android.launcher3.tracing.TouchInteractionServiceProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.android.launcher3.tracing.LauncherTrace.internal_static_com_android_launcher3_tracing_TouchInteractionServiceProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.android.launcher3.tracing.LauncherTrace.internal_static_com_android_launcher3_tracing_TouchInteractionServiceProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.android.launcher3.tracing.TouchInteractionServiceProto.class, com.android.launcher3.tracing.TouchInteractionServiceProto.Builder.class);
    }

    // Construct using com.android.launcher3.tracing.TouchInteractionServiceProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      serviceConnected_ = false;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.android.launcher3.tracing.LauncherTrace.internal_static_com_android_launcher3_tracing_TouchInteractionServiceProto_descriptor;
    }

    @java.lang.Override
    public com.android.launcher3.tracing.TouchInteractionServiceProto getDefaultInstanceForType() {
      return com.android.launcher3.tracing.TouchInteractionServiceProto.getDefaultInstance();
    }

    @java.lang.Override
    public com.android.launcher3.tracing.TouchInteractionServiceProto build() {
      com.android.launcher3.tracing.TouchInteractionServiceProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.android.launcher3.tracing.TouchInteractionServiceProto buildPartial() {
      com.android.launcher3.tracing.TouchInteractionServiceProto result = new com.android.launcher3.tracing.TouchInteractionServiceProto(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.serviceConnected_ = serviceConnected_;
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.android.launcher3.tracing.TouchInteractionServiceProto) {
        return mergeFrom((com.android.launcher3.tracing.TouchInteractionServiceProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.android.launcher3.tracing.TouchInteractionServiceProto other) {
      if (other == com.android.launcher3.tracing.TouchInteractionServiceProto.getDefaultInstance()) return this;
      if (other.hasServiceConnected()) {
        setServiceConnected(other.getServiceConnected());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.android.launcher3.tracing.TouchInteractionServiceProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.android.launcher3.tracing.TouchInteractionServiceProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private boolean serviceConnected_ ;
    /**
     * <code>optional bool service_connected = 1;</code>
     * @return Whether the serviceConnected field is set.
     */
    @java.lang.Override
    public boolean hasServiceConnected() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional bool service_connected = 1;</code>
     * @return The serviceConnected.
     */
    @java.lang.Override
    public boolean getServiceConnected() {
      return serviceConnected_;
    }
    /**
     * <code>optional bool service_connected = 1;</code>
     * @param value The serviceConnected to set.
     * @return This builder for chaining.
     */
    public Builder setServiceConnected(boolean value) {
      bitField0_ |= 0x00000001;
      serviceConnected_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool service_connected = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearServiceConnected() {
      bitField0_ = (bitField0_ & ~0x00000001);
      serviceConnected_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.android.launcher3.tracing.TouchInteractionServiceProto)
  }

  // @@protoc_insertion_point(class_scope:com.android.launcher3.tracing.TouchInteractionServiceProto)
  private static final com.android.launcher3.tracing.TouchInteractionServiceProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.android.launcher3.tracing.TouchInteractionServiceProto();
  }

  public static com.android.launcher3.tracing.TouchInteractionServiceProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<TouchInteractionServiceProto>
      PARSER = new com.google.protobuf.AbstractParser<TouchInteractionServiceProto>() {
    @java.lang.Override
    public TouchInteractionServiceProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TouchInteractionServiceProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TouchInteractionServiceProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TouchInteractionServiceProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.android.launcher3.tracing.TouchInteractionServiceProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

